name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONDEVMODE: 1
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10']
        django-version:
          - '>=4.0a1,<4.1'
          - '>=3.2,<4.0'
          - '>=3.1,<3.2'
          - '>=3.0,<3.1'
          - '>=2.2,<3.0'
          - '>=2.1,<2.2'
          - '>=2.0,<2.1'
        exclude:
          - python-version: 3.6
            django-version: '>=4.0a1,<4.1'
          - python-version: 3.7
            django-version: '>=4.0a1,<4.1'
          - python-version: '3.10'
            django-version: '>=3.2,<4.0'
          - python-version: '3.10'
            django-version: '>=3.1,<3.2'
          - python-version: '3.10'
            django-version: '>=3.0,<3.1'
          - python-version: '3.10'
            django-version: '>=2.2,<3.0'
          - python-version: '3.10'
            django-version: '>=2.1,<2.2'
          - python-version: '3.10'
            django-version: '>=2.0,<2.1'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies (Django ${{ matrix.django-version }})
      run: |
        python -m pip install --upgrade pip
        python -m pip install --pre django'${{ matrix.django-version }}'
        python -m pip install flake8 coverage -e .
    - name: Lint with flake8
      run: |
        flake8
    - name: Test with unittest
      run: |
        coverage run tests/manage.py test django_python3_ldap
        coverage report
